Revert "default: remove config"
This reverts commit b5a9dd32bae2c056e0eb60ad9809ed3e73826af8. Without
the default config, the following error is seen when updating packages:

    $ nix-env -u -v
    evaluating file '/nix/store/fc33jq7fj9vi7nj7vmy69hj6igy7mgyp-nix-2.3.16/share/nix/corepkgs/derivation.nix'
    evaluating file '/nix/store/16bq50yjp3yhywi8bccvbvvbimpw0xdh-env-manifest.nix'
    evaluating file '/home/alex/.nix-defexpr/channels_root/machines/modules/awesome.nix'
    evaluating file '/home/alex/.nix-defexpr/channels_root/machines/modules/btrfs.nix'
    evaluating file '/home/alex/.nix-defexpr/channels_root/machines/modules/common.nix'
    error: cannot auto-call a function that has an argument without a default value ('pkgs')